--CREATE DATABASE linketinder;

CREATE TABLE IF NOT EXISTS dados_candidatos(
	id SERIAL PRIMARY KEY,
	nome CHARACTER VARYING(50) NOT NULL,
	sobrenome CHARACTER VARYING(50) NOT NULL,
	data_nascimento date NOT NULL,
	email CHARACTER VARYING(50) NOT NULL,
	cpf CHARACTER VARYING(14) NOT NULL,
	pais CHARACTER VARYING(50) NOT NULL,
	cep CHARACTER VARYING(11) NOT NULL,
	descricao CHARACTER VARYING(50) NOT NULL,
	senha CHARACTER VARYING(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS dados_empresas(
	id SERIAL PRIMARY KEY,
	nome CHARACTER VARYING(50) NOT NULL,
	cnpj CHARACTER VARYING(14) NOT NULL,
	email CHARACTER VARYING(50) NOT NULL,
	descricao CHARACTER VARYING(50) NOT NULL,
	pais CHARACTER VARYING(50) NOT NULL,
	cep CHARACTER VARYING(11) NOT NULL,
	senha CHARACTER VARYING(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS competencias(
	id SERIAL PRIMARY KEY,
	nome CHARACTER VARYING(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS vagas(
	id SERIAL PRIMARY KEY,
	nome CHARACTER VARYING(50) NOT NULL,
	descricao CHARACTER VARYING(50) NOT NULL,
	local_vaga INT REFERENCES dados_empresas(id) NOT NULL
);

CREATE TABLE IF NOT EXISTS competencias_candidatos(
	competencia INT REFERENCES competencias(id) NOT NULL,
	vaga INT REFERENCES dados_candidatos(id) NOT NULL
);

CREATE TABLE IF NOT EXISTS competencias_vagas(
	competencia INT REFERENCES competencias(id) NOT NULL,
	vaga INT REFERENCES vagas(id) NOT NULL
);